#define STICK_X_ADC_CHANNEL             ADC1_CHANNEL_6
#define STICK_Y_ADC_CHANNEL             ADC1_CHANNEL_7
#define STICK_Z_ADC_CHANNEL             ADC1_CHANNEL_0
#define STICK_GRABBER_ADC_CHANNEL       ADC1_CHANNEL_3

#define STICK_X_CENTER_VALUE            1900
#define STICK_Y_CENTER_VALUE            1717
#define STICK_Z_CENTER_VALUE            1850
#define STICK_GRABBER_CENTER_VALUE      0